on:
  schedule:
    - cron:  '0 0 * * 3' # at 12am every wednesday. Ref https://crontab.guru/examples.html

name: Get csv from spotify

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Scrape
      run: npm run action
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
